Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,19 +42,27 @@ jobs:
   #           exit 1
   #         fi
 
-  # checkdocumentation:
-  #   name: Check Documentation
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     # Checkout the current branch
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
-  #     # Set up python environment
-  #     - name: Set up Python
-  #       uses: actions/setup-python@v4
-  #       with:
-  #         python-version: '3.10'
-  #     # Run your test
-  #     - name: Check Documentation
-  #       run: #TODO: Add your test here (simply call the python file we provided)
+  checkdocumentation:
+    name: Check Documentation
+    runs-on: ubuntu-latest
+    steps:
+      # Checkout the current branch
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      # Set up python environment
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+      # Run your test
+      - name: Check Documentation
+        run: | #TODO: Add your test here (simply call the python file we provided)
+          if grep -f 'Documentation.md'; then\
+           echo "there is a Documentation.md file"
+           exit 0
+          else 
+           echo "there is no required Documentation.md"
+           exit 1
+          fi 
+
